'use strict';

const createdAt = new Date();
const updatedAt = new Date();

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
     await queryInterface.bulkInsert('money', [{
        cost: "50000",
        memo: "잃어버린 돈",
        date: "2021-07-12",
        userId: "1",
        categoryId: "1",
        createdAt,
        updatedAt,
     },{
        cost: "100000",
        memo: "조카 용돈",
        date: "2021-07-15",
        userId: "1",
        categoryId: "1",
        createdAt,
        updatedAt,
     },{
        cost: "79000",
        memo: "랍스타",
        date: "2021-07-11",
        userId: "1",
        categoryId: "2",
        createdAt,
        updatedAt,
    },{
        cost: "200",
        memo: "츄파츕스",
        date: "2021-07-24",
        userId: "1",
        categoryId: "2",
        createdAt,
        updatedAt,
    },{
        cost: "70000",
        memo: "헬스장",
        date: "2021-07-02",
        userId: "1",
        categoryId: "3",
        createdAt,
        updatedAt,
    },{
        cost: "20000",
        memo: "퍼즐",
        date: "2021-07-18",
        userId: "1",
        categoryId: "3",
        createdAt,
        updatedAt,
    },{
        cost: "38000",
        memo: "장보기",
        date: "2021-07-05",
        userId: "1",
        categoryId: "4",
        createdAt,
        updatedAt,
      },{
        cost: "20000",
        memo: "졸리 간식",
        date: "2021-07-12",
        userId: "1",
        categoryId: "4",
        createdAt,
        updatedAt,
      },{
        cost: "400000",
        memo: "월세",
        date: "2021-07-01",
        userId: "1",
        categoryId: "5",
        createdAt,
        updatedAt,
      },{
        cost: "9500",
        memo: "유튜브 프리미엄",
        date: "2021-07-01",
        userId: "1",
        categoryId: "5",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "책상",
        date: "2021-07-15",
        userId: "1",
        categoryId: "6",
        createdAt,
        updatedAt,
      },{
        cost: "720000",
        memo: "옷",
        date: "2021-07-28",
        userId: "1",
        categoryId: "6",
        createdAt,
        updatedAt,
      },{
        cost: "500000",
        memo: "적금",
        date: "2021-07-01",
        userId: "1",
        categoryId: "7",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "주식",
        date: "2021-07-07",
        userId: "1",
        categoryId: "7",
        createdAt,
        updatedAt,
      },{
        cost: "41900",
        memo: "택시비",
        date: "2021-07-11",
        userId: "1",
        categoryId: "8",
        createdAt,
        updatedAt,
      },{
        cost: "217200",
        memo: "기름값",
        date: "2021-07-29",
        userId: "1",
        categoryId: "8",
        createdAt,
        updatedAt,
      },{
        cost: "119000",
        memo: "뮤지컬",
        date: "2021-07-12",
        userId: "1",
        categoryId: "9",
        createdAt,
        updatedAt,
      },{
        cost: "28000",
        memo: "영화",
        date: "2021-07-30",
        userId: "1",
        categoryId: "9",
        createdAt,
        updatedAt,
      },{
        cost: "50000",
        memo: "친구 결혼",
        date: "2021-07-22",
        userId: "1",
        categoryId: "10",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "민규 생일",
        date: "2021-07-11",
        userId: "1",
        categoryId: "10",
        createdAt,
        updatedAt,
      },{
        cost: "50000",
        memo: "지갑 잃어버렸다..",
        date: "2021-07-12",
        userId: "2",
        categoryId: "11",
        createdAt,
        updatedAt,
     },{
        cost: "100000",
        memo: "조카 용돈",
        date: "2021-07-15",
        userId: "2",
        categoryId: "11",
        createdAt,
        updatedAt,
     },{
        cost: "79000",
        memo: "랍스타",
        date: "2021-07-11",
        userId: "2",
        categoryId: "12",
        createdAt,
        updatedAt,
    },{
        cost: "200",
        memo: "츄파츕스",
        date: "2021-07-24",
        userId: "2",
        categoryId: "12",
        createdAt,
        updatedAt,
    },{
        cost: "70000",
        memo: "헬스장",
        date: "2021-07-02",
        userId: "2",
        categoryId: "13",
        createdAt,
        updatedAt,
    },{
        cost: "20000",
        memo: "퍼즐",
        date: "2021-07-18",
        userId: "2",
        categoryId: "13",
        createdAt,
        updatedAt,
    },{
        cost: "38000",
        memo: "장보기",
        date: "2021-07-05",
        userId: "2",
        categoryId: "14",
        createdAt,
        updatedAt,
      },{
        cost: "20000",
        memo: "졸리 간식",
        date: "2021-07-12",
        userId: "2",
        categoryId: "14",
        createdAt,
        updatedAt,
      },{
        cost: "400000",
        memo: "월세",
        date: "2021-07-01",
        userId: "2",
        categoryId: "15",
        createdAt,
        updatedAt,
      },{
        cost: "9500",
        memo: "유튜브 프리미엄",
        date: "2021-07-01",
        userId: "2",
        categoryId: "15",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "책상",
        date: "2021-07-15",
        userId: "2",
        categoryId: "16",
        createdAt,
        updatedAt,
      },{
        cost: "720000",
        memo: "옷",
        date: "2021-07-28",
        userId: "2",
        categoryId: "16",
        createdAt,
        updatedAt,
      },{
        cost: "500000",
        memo: "적금",
        date: "2021-07-01",
        userId: "2",
        categoryId: "17",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "주식",
        date: "2021-07-07",
        userId: "2",
        categoryId: "17",
        createdAt,
        updatedAt,
      },{
        cost: "41900",
        memo: "택시비",
        date: "2021-07-11",
        userId: "2",
        categoryId: "18",
        createdAt,
        updatedAt,
      },{
        cost: "217200",
        memo: "기름값",
        date: "2021-07-29",
        userId: "2",
        categoryId: "18",
        createdAt,
        updatedAt,
      },{
        cost: "119000",
        memo: "뮤지컬",
        date: "2021-07-12",
        userId: "2",
        categoryId: "19",
        createdAt,
        updatedAt,
      },{
        cost: "28000",
        memo: "영화",
        date: "2021-07-30",
        userId: "2",
        categoryId: "19",
        createdAt,
        updatedAt,
      },{
        cost: "50000",
        memo: "친구 결혼",
        date: "2021-07-22",
        userId: "2",
        categoryId: "20",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "민규 생일",
        date: "2021-07-11",
        userId: "2",
        categoryId: "20",
        createdAt,
        updatedAt,
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
     await queryInterface.bulkDelete('money', null, {});
  }
};
