'use strict';

const createdAt = new Date();
const updatedAt = new Date();

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
     await queryInterface.bulkInsert('money', [
        {
        cost: "50000",
        memo: "길가다 주운 돈",
        date: "2021-07-07",
        userId: "4",
        categoryId: "1",
        createdAt,
        updatedAt,
     }, {
        cost: "100000",
        memo: "큰아빠가 준 용돈",
        date: "2021-07-18",
        userId: "4",
        categoryId: "1",
        createdAt,
        updatedAt,
     }, {
        cost: "79000",
        memo: "빠스타 with 여친",
        date: "2021-07-13",
        userId: "4",
        categoryId: "2",
        createdAt,
        updatedAt,
    }, {
        cost: "4800",
        memo: "편의점 커피",
        date: "2021-07-24",
        userId: "4",
        categoryId: "2",
        createdAt,
        updatedAt,
    }, {
        cost: "150000",
        memo: "빌어먹을 핸드폰 약정",
        date: "2021-07-02",
        userId: "4",
        categoryId: "3",
        createdAt,
        updatedAt,
    }, {
        cost: "20000",
        memo: "태블릿 데이터 비용",
        date: "2021-07-18",
        userId: "4",
        categoryId: "3",
        createdAt,
        updatedAt,
    }, {
        cost: "15000",
        memo: "버스비",
        date: "2021-07-19",
        userId: "4",
        categoryId: "4",
        createdAt,
        updatedAt,
      },{
        cost: "60000",
        memo: "택시비",
        date: "2021-07-04",
        userId: "4",
        categoryId: "4",
        createdAt,
        updatedAt,
      },{
        cost: "40000",
        memo: "조카 유치원 픽업",
        date: "2021-07-01",
        userId: "4",
        categoryId: "5",
        createdAt,
        updatedAt,
      },{
        cost: "9500",
        memo: "유튜브 프리미엄",
        date: "2021-07-01",
        userId: "4",
        categoryId: "5",
        createdAt,
        updatedAt,
      },{
        cost: "165000",
        memo: "토익학원 접수",
        date: "2021-07-01",
        userId: "4",
        categoryId: "6",
        createdAt,
        updatedAt,
      },{
        cost: "168000",
        memo: "제빵 학원",
        date: "2021-07-15",
        userId: "4",
        categoryId: "6",
        createdAt,
        updatedAt,
      },{
        cost: "48000",
        memo: "쿠우쿠우 먹방",
        date: "2021-07-12",
        userId: "4",
        categoryId: "7",
        createdAt,
        updatedAt,
      },{
        cost: "91200",
        memo: "스떼이크를 썰어봤습니다",
        date: "2021-07-07",
        userId: "4",
        categoryId: "7",
        createdAt,
        updatedAt,
      },{
        cost: "165000",
        memo: "미슐랭 한식집 탐방!!!",
        date: "2021-07-11",
        userId: "4",
        categoryId: "7",
        createdAt,
        updatedAt,
      },{
        cost: "36900",
        memo: "요번달 하이패스비 !",
        date: "2021-07-29",
        userId: "4",
        categoryId: "8",
        createdAt,
        updatedAt,
      },{
        cost: "119000",
        memo: "캣츠가 왜 유명한지 알겠더라구요",
        date: "2021-07-12",
        userId: "4",
        categoryId: "9",
        createdAt,
        updatedAt,
      },{
        cost: "4500000",
        memo: "가죽 쪼가리가 왜 가격이 왜이래 !",
        date: "2021-07-23",
        userId: "4",
        categoryId: "9",
        createdAt,
        updatedAt,
      },{
        cost: "50000",
        memo: "친구 결혼",
        date: "2021-07-19",
        userId: "4",
        categoryId: "10",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "민규 생일",
        date: "2021-07-11",
        userId: "4",
        categoryId: "10",
        createdAt,
        updatedAt,
      },{
        cost: "760000",
        memo: "지갑 잃어버렸다..",
        date: "2021-07-21",
        userId: "4",
        categoryId: "11",
        createdAt,
        updatedAt,
     },{
        cost: "100000",
        memo: "조카 용돈",
        date: "2021-07-15",
        userId: "4",
        categoryId: "11",
        createdAt,
        updatedAt,
        ////////////////// user 4번 /////////////////
     }, {
        cost: "79000",
        memo: "랍스타",
        date: "2021-07-11",
        userId: "5",
        categoryId: "12",
        createdAt,
        updatedAt,
    },{
        cost: "200",
        memo: "츄파츕스",
        date: "2021-07-24",
        userId: "5",
        categoryId: "12",
        createdAt,
        updatedAt,
    },{
        cost: "70000",
        memo: "헬스장",
        date: "2021-07-02",
        userId: "5",
        categoryId: "13",
        createdAt,
        updatedAt,
    },{
        cost: "20000",
        memo: "퍼즐",
        date: "2021-07-18",
        userId: "5",
        categoryId: "13",
        createdAt,
        updatedAt,
    },{
        cost: "38000",
        memo: "장보기",
        date: "2021-07-05",
        userId: "5",
        categoryId: "14",
        createdAt,
        updatedAt,
      },{
        cost: "20000",
        memo: "졸리 간식",
        date: "2021-07-12",
        userId: "5",
        categoryId: "14",
        createdAt,
        updatedAt,
      },{
        cost: "400000",
        memo: "월세",
        date: "2021-07-01",
        userId: "5",
        categoryId: "15",
        createdAt,
        updatedAt,
      },{
        cost: "9500",
        memo: "유튜브 프리미엄",
        date: "2021-07-01",
        userId: "5",
        categoryId: "15",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "책상",
        date: "2021-07-15",
        userId: "5",
        categoryId: "16",
        createdAt,
        updatedAt,
      },{
        cost: "720000",
        memo: "옷",
        date: "2021-07-28",
        userId: "5",
        categoryId: "16",
        createdAt,
        updatedAt,
      },{
        cost: "500000",
        memo: "적금",
        date: "2021-07-01",
        userId: "5",
        categoryId: "17",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "주식",
        date: "2021-07-07",
        userId: "5",
        categoryId: "17",
        createdAt,
        updatedAt,
      },{
        cost: "41900",
        memo: "택시비",
        date: "2021-07-11",
        userId: "5",
        categoryId: "18",
        createdAt,
        updatedAt,
      },{
        cost: "217200",
        memo: "기름값",
        date: "2021-07-29",
        userId: "5",
        categoryId: "18",
        createdAt,
        updatedAt,
      },{
        cost: "119000",
        memo: "뮤지컬",
        date: "2021-07-12",
        userId: "5",
        categoryId: "19",
        createdAt,
        updatedAt,
      },{
        cost: "28000",
        memo: "영화",
        date: "2021-07-30",
        userId: "5",
        categoryId: "19",
        createdAt,
        updatedAt,
      },{
        cost: "50000",
        memo: "친구 결혼",
        date: "2021-07-22",
        userId: "5",
        categoryId: "20",
        createdAt,
        updatedAt,
      },{
        cost: "100000",
        memo: "민규 생일",
        date: "2021-07-11",
        userId: "5",
        categoryId: "20",
        createdAt,
        updatedAt,
      },
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
     await queryInterface.bulkDelete('money', null, {});
  }
};
